[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "php-collection"
authors = [{name = "Steevan BARBOYON", email = "steevan.barboyon@gmail.com"}]
dynamic = ["version", "description"]
